[project]
name = "amptool"
version = "0.1.0"
description = "Generating 3D models of amphiphilic polypeptides"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "M. Feliks", email = "mfeliks83@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2",
    "rdkit>=2025.3",
]
classifiers = ["Private :: Do Not Upload"]

[project.urls]
homepage = "https://github.com/efliks/amptool"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
tests = [
    "pytest>=8.3.5",
    "pytest-cov>=6.1.0",
]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.15.0",
]
